### ISSUE TITLE
seems not to work on node 16?

### ISSUE THREAD

**Issue by scamden** [ghaiklor/node-x509#10]
getting error `Module did not self-register`

**Comment by scamden** [comment]
@ghaiklor are you still maintaining this?

**Comment by ghaiklor** [comment]
@scamden I did the fork to fix the long standing issue in the original package, but I'm not maintaining this. If you are willing to fix it via PR, I'll gladly merge it and publish the update.

**Comment by scamden** [comment]
tbh not sure how to go about that, we already switched to an all JS alternative and don't have the time to get engaged with this. apologies and thanks for your initial work

**Comment by ghaiklor** [comment]
no problem
